export const cases=[
{id:'terminal',title:'The terminal acquisition',level:'01 / VALUATION',minutes:25,anchor:'jeddah',intro:'You are advising a fund on a mature container terminal with 20 years left on its concession. Build cash flow from containers handled, decide what the business is worth, then finance the purchase.',task:'Would you buy this terminal at 11× current EBITDA with 55% acquisition debt? Give an investment recommendation and identify the downside that matters most.',focus:'Finite concession DCF · leverage · sponsor returns',questions:[['Why is EBITDA not cash flow?','EBITDA excludes tax, equipment replacement and working capital. A terminal with heavy crane replacement can have high EBITDA but weak distributable cash flow.'],['Why is there no perpetual terminal value?','The operating right expires. This case assumes no renewal or compensation. A sale in year 5 transfers only the remaining 15 years of cash flow.'],['Why can the IRR be disappointing even with debt?','Leverage magnifies the difference between the asset return and financing cost. Paying too much or making aggressive amortization payments can suppress equity distributions.'],['What do you diligence first?','Concession term and handback obligations; customer concentration and minimum volumes; tariff freedom; maintenance and expansion capex; labor and capacity bottlenecks.']]},
{id:'minority',title:'What does a 25% stake cost?',level:'02 / M&A',minutes:15,anchor:'maasvlakte',intro:'An operator sells 25% of a terminal. The headline gives the ownership percentage but no price. Your interviewer asks you to build the enterprise-to-equity bridge.',focus:'Enterprise value · net debt · minority governance',task:'Assume enterprise value of €800m, debt of €260m and unrestricted cash of €40m. What is 25% of equity worth before deal-specific adjustments?',steps:[['Enterprise value','€800m','The value of the operating business available to debt and equity holders.'],['Net debt','€260m − €40m = €220m','Cash reduces the debt-like claim only if it is freely distributable; restricted cash needs separate treatment.'],['Equity value','€800m − €220m = €580m','What remains for all ordinary shareholders before other claims or adjustments.'],['Pro-rata stake','25% × €580m = €145m','A starting point, not a quoted transaction price. Control rights, dilution and commitments can change the price.']],questions:[['Is 25% of €800m the right answer?','No. €800m is enterprise value. A stake in shares is priced from equity value.'],['Would you apply a minority discount automatically?','No. Assess veto rights, board representation, dividends, transfer restrictions, puts and calls, commercial agreements and auction dynamics.'],['What if the buyer commits €50m of new equity?','Separate cash paid to existing sellers from primary capital invested into the company. Recalculate pre-money and post-money ownership.']]},
{id:'debt',title:'Size the debt before the ribbon cutting',level:'03 / PROJECT FINANCE',minutes:20,anchor:'klaipeda',intro:'A port authority plans a €201m infrastructure programme. The public announcement identifies a €100m EIB loan. Your job is to map the rest of the funding and test debt service.',focus:'Sources & uses · CFADS · DSCR · debt capacity',task:'For practice only, assume €35m grants, €100m debt, annual cash available for debt service of €12m, a 1.30× DSCR target, a 5% interest rate and a 15-year level-payment loan.',steps:[['Funding gap','€201m − €100m − €35m = €66m','This simplified case assumes the remainder is equity; real programmes can include other loans and public funding.'],['Maximum annual debt service','€12m / 1.30 = €9.23m','DSCR = cash available for debt service divided by interest plus scheduled principal.'],['Indicative debt capacity','€9.23m × [1 − (1.05)^−15] / 5% ≈ €95.8m','The present value of a level annual debt-service stream; assumes flat CFADS, end-year payments and no reserve funding.'],['Financing consequence','€100m exceeds €95.8m','Either reduce debt, increase CFADS, lengthen tenor or change the amortization. Do not assume the public EIB facility has these hypothetical terms.']],questions:[['Does a 1.30× DSCR mean a 30% equity return?','No. It means €1.30 of available cash for each €1.00 of scheduled debt service. It is a lender coverage ratio.'],['How is CFADS different from EBITDA?','For this simplified model it is EBITDA less cash tax, maintenance capex and working capital movements. Loan documents can define it differently.'],['What else does the lender need?','Downside cases, construction contingency, completion support, reserve accounts, security, covenant definitions and a debt tail before concession expiry.']]},
{id:'automation',title:'Does terminal automation actually pay?',level:'04 / INVESTMENT COMMITTEE',minutes:20,anchor:'southampton',intro:'The operating team proposes €30m of new equipment and automation. The sales pitch promises faster handling. Translate the operational claim into cash.',focus:'Incremental cash flow · NPV · payback · bottlenecks',task:'Assume 100,000 additional paid TEU at €35 contribution per TEU, €2m annual labor savings, €1m extra operating costs, €0.5m maintenance capex, €3m depreciation and 25% tax. Benefits last 10 years; discount at 9%.',steps:[['Incremental EBITDA','0.1m × €35 + €2m − €1m = €4.5m','Contribution per TEU is revenue less volume-dependent cost, not the full tariff.'],['Cash tax','(€4.5m − €3m) × 25% = €0.375m','Assumes positive taxable operating profit and depreciation equal to €3m annually.'],['Annual incremental cash flow','€4.5m − €0.375m − €0.5m = €3.625m','Assumes no additional working capital and no residual value.'],['Investment NPV','€3.625m × 6.418 − €30m ≈ −€6.73m','At a 9% hurdle rate, these assumptions do not justify the investment. Undiscounted payback is about 8.3 years.']],questions:[['What if the yard is already full?','Faster quay cranes may shift the queue to the yard. Model the entire system: berth, yard, gate, rail and labor.'],['What proves the savings?','A measured baseline, realistic ramp-up, downtime assumptions, signed labor arrangements and pilot or comparable-site performance. Vendor claims alone are insufficient.'],['How would you improve the case?','Test higher contribution, lower capex, staged rollout or higher utilization. Distinguish actual efficiency gains from moving costs between budgets.']]},
{id:'digital',title:'A data center is not a terminal',level:'05 / CROSS-SECTOR',minutes:15,anchor:'atnorth',intro:'A fund compares port infrastructure with a data center platform. Both are capital intensive, but they earn cash in different ways.',focus:'Contracted EBITDA · growth capex · power risk',task:'For practice, assume a platform has €80m operating EBITDA and €160m contracted future EBITDA. The asking EV is €2bn. Explain which multiple is meaningful.',steps:[['Operating multiple','€2,000m / €80m = 25.0×','Based on EBITDA already being earned, subject to normalization.'],['Contracted future multiple','€2,000m / €160m = 12.5×','Looks cheaper, but may depend on unbuilt capacity, energization and customer ramp-up.'],['Build-to-earn obligation','Add required growth capex and timing','The future EBITDA does not arrive for free. Include committed capex, financing costs and construction risk.'],['Cross-sector judgment','Compare cash-flow quality, not just multiples','Ports depend on throughput, tariffs and concessions; data centers depend on power, contracted capacity, tenant quality and delivery obligations.']],questions:[['Can I compare 12.5× future EBITDA to 12.5× current port EBITDA?','Only after aligning dates, maturity, remaining capex, contract risk and accounting definitions. Headline multiples alone are not comparable.'],['What is the first diligence question?','Which contracts are unconditional, when does revenue start, and how much funded and unfunded capex is needed before that happens?']]},
{id:'refinance',title:'The refinancing that fails the downside',level:'06 / CREDIT',minutes:15,anchor:'lastmile',intro:'A utility borrower has predictable customers but rising interest expense. A lender wants to know whether recurring revenue really supports more debt.',focus:'Interest cover · amortization · stress testing',task:'Assume debt of €300m, 6% interest, annual principal payments of €12m and CFADS of €42m. Stress interest to 8% and CFADS down 15%.',steps:[['Base debt service','€300m × 6% + €12m = €30m','Debt service includes both interest and principal.'],['Base DSCR','€42m / €30m = 1.40×','A 1.30× illustrative minimum would be satisfied.'],['Downside debt service','€300m × 8% + €12m = €36m','This assumes all debt reprices and the opening balance is unchanged.'],['Downside DSCR','(€42m × 85%) / €36m = 0.99×','Cash falls slightly short of scheduled payments. A stable sector is not a guarantee of a resilient capital structure.']],questions:[['Would an interest-rate hedge fix everything?','It can reduce rate exposure, but it does not restore missing operating cash flow or remove refinancing, counterparty and liquidity risks.'],['What remedies would you propose?','Reduce leverage, extend amortization within asset life, establish liquidity reserves, hedge floating rates and test covenant headroom. Check feasibility and costs.']]}
];
export const glossary=[
['TEU','Twenty-foot equivalent unit. A standard measure of container volume; a forty-foot container generally counts as two TEU.','Revenue = paid TEU × average net revenue per TEU.'],
['Enterprise value (EV)','Value of the operating business to all capital providers. It is not the cheque paid for shares.','Equity value = EV − debt + unrestricted cash, before other claims and adjustments.'],
['EBITDA','Earnings before interest, tax, depreciation and amortization. A starting measure of operating earnings.','Revenue − cash operating costs. It is not free cash flow.'],
['EBIT','Operating profit after depreciation and amortization.','EBIT = EBITDA − depreciation − amortization.'],
['Capex','Cash spent on long-lived assets such as cranes, berths or servers.','Separate maintenance needed to preserve earnings from expansion intended to grow them.'],
['Working capital','Cash tied up in ordinary operations, for example receivables less supplier financing.','An increase is a cash outflow. Profit booked before a customer pays is not cash collected.'],
['FCFF','Free cash flow to the firm: operating cash available to lenders and equity investors before debt payments.','EBIT × (1 − tax rate) + depreciation − capex − change in working capital.'],
['WACC','Weighted average cost of capital. A discount rate for unlevered operating cash flows consistent with their risk and currency.','Higher WACC reduces present value. Match nominal cash flows to a nominal discount rate.'],
['DCF','Discounted cash flow valuation adds up future cash flows expressed in today’s money.','PV = cash flow in year t / (1 + discount rate)^t.'],
['CFADS','Cash flow available for debt service, defined by a financing agreement.','In this lab: EBITDA − cash tax − maintenance capex − change in working capital.'],
['DSCR','Debt service coverage ratio: the cash buffer for scheduled debt payments.','DSCR = CFADS / (interest + scheduled principal). Below 1× means a shortfall.'],
['IRR','The annual discount rate that makes the net present value of investment cash flows zero.','Timing matters. Multiple sign changes can produce ambiguous results; not every cash-flow series has a unique IRR.'],
['MOIC','Multiple on invested capital: total cash received divided by total cash invested.','2× says money doubled, but does not tell you whether it took 3 or 15 years.'],
['Concession','A contractual right to operate an asset for a defined period under agreed conditions.','Review expiry, tariffs, renewal, capex, handback, termination compensation and change-of-control clauses.'],
['Financial close','The point at which financing agreements become effective and conditions for funding are satisfied.','A memorandum of understanding or announced transaction is not financial close.'],
['Basis points','A unit used for changes in interest rates: 100 basis points equals one percentage point.','A move from 5% to 6% is +100 basis points.'],
['Equity bridge','The adjustments from operating-business value to the value attributable to shareholders.','EV − net debt − other debt-like items − minority claims + nonoperating assets, subject to the deal perimeter.'],
['Debt tail','Time between the scheduled final loan repayment and the end of the asset’s contracted life.','It gives lenders a buffer if cash collection or debt repayment is delayed.']
];
